version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git   # (1)
    working_directory: ~/ds-circleci-images
    steps:
      - checkout
      - setup_remote_docker   # (2)

      # build and push Docker image
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io

          docker build -t quay.io/hotosm/circleci:node9.10-python2.7 - < images/node9.10-python2.7
          docker push quay.io/hotosm/circleci:node9.10-python2.7

          docker build -t quay.io/hotosm/circleci:node9.10-azure-cli - < images/node9.10-azure-cli
          docker push quay.io/hotosm/circleci:node9.10-azure-cli
